### ISSUE TITLE
[Bug] Fresh installation troubles

### ISSUE THREAD

**Issue by istickz** [creativetimofficial/ct-vue-soft-ui-dashboard-pro#1]
### Version
vue-soft-ui-dashboard-pro-v1.0.0
### Reproduction link
https://example.com
### Operating System
Os X
### Device
Laptop
### Browser & Version
-
### Steps to reproduce
Donwnload theme
$ cd vue-soft-ui-dashboard-pro-v1.0.0
$ npm install
### What is expected?
all modules installed
### What is actually happening?
 npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-soft-ui-dashboard-pro@1.0.0
npm ERR! Found: vue@3.2.0
npm ERR! node_modules/vue
npm ERR!   vue@"3.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.6.12" from @fullcalendar/vue@5.10.1
npm ERR! node_modules/@fullcalendar/vue
npm ERR!   @fullcalendar/vue@"5.10.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/temur/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/temur/.npm/_logs/2022-02-16T01_41_29_131Z-debug.log

---
### Solution
Remove "@fullcalendar/vue": "5.10.1" and keep "@fullcalendar/vue3": "5.10.1",
```
    "@fullcalendar/vue": "5.10.1",
    "@fullcalendar/vue3": "5.10.1",
```

**Comment by sajadevo** [comment]
**Hi @istickz **

Thanks for using the product and helping us for make it better we'll take care of that on the next update of the product.

Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/FhCJCaHdQa).

All the best,
Sajad
