### ISSUE TITLE
v-model in VsudInput component

### ISSUE THREAD

**Issue by torgem** [creativetimofficial/ct-vue-soft-ui-dashboard-pro#2]
Is it not possible to use the v-model binding in the VsudInput component? In order to use the v-model binding within the VsudInput.vue component I had to change the <input> Tag in VsudInput.vue -> :value="modelValue" @input="$emit('update:modelValue', $event.target.value)" Then, I changed the name of the "value" property to "modelValue".

**Comment by sajadevo** [comment]
**Hi @torgem**

Thanks for using our product, of course you can customize all of the components the way you want, here is a quick guide for the topic you want: [v-model](https://learnvue.co/2021/01/everything-you-need-to-know-about-vue-v-model/).

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
