### ISSUE TITLE
Messages page missing?

### ISSUE THREAD

**Issue by kmaher9** [creativetimofficial/ct-vue-soft-ui-dashboard-pro#3]
I've just downloaded 2.0.0 and the Pages/Messages route, https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/pages/messages.html, this file is not present.

**Comment by sajadevo** [comment]
**Hi @kmaher9**

The messages page is not included for the VueJS version yet it will be available on the next update of the product.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
